package DZ_10.Test_Exeption_try_catch;

public class Foo1 {
    public static void main(String[] args) {
        try {
            return;
        } finally {
            System.out.println("Finally");
        }

    }
}
