package DZ_10.Test_Exeption_try_catch;

public class Foo9 {
    public static void main(String[] args) {
        try {
            System.out.print("Hello world ");
        } finally {
            System.out.println("Finally executing ");
        }

    }
}
